###
POST http://localhost:8080/upload
Content-Type: application/json

{
  "packages": [],
  "classes": [],
  "properties": [],
  "enumerations": [],
  "associations": []
}

###


###
GET http://localhost:8080/entries
Accept: application/json

###


###
POST http://localhost:8080/entries
Content-Type: application/json

{}

###