//==============================================================================
// Copyright (c) 2020 BMW Group. All rights reserved.
//==============================================================================
/**
 * Replace the base package: com.bmw.ca with your project name like e.g. com.bmw.vehicles
 * Replace the "microsonic" with the name of the microservice. Should correspond with artifactId in the
 * pom.xml and the folder name. As generated by the archetype.
 */
package com.bmw.ptad;
